# Configuration file of @PROJECT_NAME@ v@VERSION@ (@DATE@)
# 
# EXPLANTATION OF THE SETTINGS
# ... scroll down for the actual settings ...
# 
# webServer:
#   Here the internal web server is configured. You can set
#   at what port it listens. If you have set the port to 8088,
#   then the map should appear in your web browser at
#   http://<your-server-ip>:8088/
#   If it does not, then that port is probably blocked. Look
#   for errors in your console, try a different port or contact
#   your hosting provider.
# 
# worlds:
#   Here each world can be configured. The world named "default"
#   is used for all worlds that do not have their own settings.
#   The most important setting is the radius. The radius is set
#   in blocks, and controls how much of the world is rendered
#   around the center.
# 
# 
# 
# ACTUAL SETTINGS BELOW
webserver:
  port: 8088
worlds:
  default:
    radius: 2147483647
    colors:
      AIR: '#000000'
      STONE: '#808080'
      GRASS: '#7fb238'
      DIRT: '#800000'
      WATER: '#0000ff'
      STATIONARY_WATER: '#0000ff'
      LAVA: '#ffa500'
      STATIONARY_LAVA: '#ffa500'
      SAND: '#f7e9a3'
      LEAVES: '#007c00'
      SANDSTONE: '#f7e9a3'
      ICE: '#a0a0ff'
      SNOW_BLOCK: '#ffffff'
      PACKED_ICE: '#a0a0ff'
      FROSTED_ICE: '#a0a0ff'