# Configuration file of ${project.name} v${project.version}
# 
# EXPLANTATION OF THE SETTINGS
# ... scroll down for the actual settings ...
# 
# webServer:
#   Here the internal web server is configured. You can set
#   at what port it listens. If you have set the port to 8088,
#   then the map should appear in your web browser at
#   http://<your-server-ip>:8088/
#   If it does not, then that port is probably blocked. Look
#   for errors in your console, try a different port or contact
#   your hosting provider.
# 
# worlds:
#   Here each world can be configured. The world named "default"
#   is used for all worlds that do not have their own settings.
#   The most important setting is the radius. The radius is set
#   in blocks, and controls how much of the world is rendered
#   around the center.
# 
# 
# 
# ACTUAL SETTINGS BELOW
webserver:
  port: 8088
worlds:
  world:
    radius: 2147483647
  world_nether:
    radius: 0
  world_the_end:
    radius: 0