# Configuration file of @PROJECT_NAME@ v@VERSION@ (@DATE@)
# 
# EXPLANATION OF THE SETTINGS
# ... scroll down for the actual settings ...
# 
# web-server:
#   Here the internal web server is configured.
#   port: 
#     The port at which the web server listens. If you have set the port to
#     8088, then the map should appear in your web browser at
#     http://<your-server-ip>:8088/ . If it does not, then that port is probably
#     blocked. Look for errors in your console, try a different port or contact
#     your hosting provider.
#   web-root:
#     The map images are placed in this directory. Normally, this directory
#     resides inside plugins/@PROJECT_NAME@/ , but you can set the web root to
#     any writeable directory.
# 
# worlds:
#   Here each world can be configured. The world named "default" is used for all
#   worlds that do not have their own settings. The most important setting is
#   the radius. The radius is set in blocks, and controls how much of the world
#   is rendered around the center. A radius of 0 disables the map for that world.
# 
#   The setting max-blocking-time-nanoseconds-per-tick specifies for how long 
#   the plugin may block the whole server (in technical terms: run on the main
#   thread). The default value is 1 ms = 1000000 ns. A tick normally takes up to
#   50 ms, so there is still at least 49 ms available for all other processes on
#   the server. Increase this value to increase map rendering speed.
#
# ACTUAL SETTINGS BELOW
web-server:
  port: 8088
  web-root: web
  internal-web-server: true
worlds:
  default:
    radius: 2147483647
    max-blocking-time-nanoseconds-per-tick: 1000000
    colors:
      AIR: '#000000'
      STONE: '#808080'
      GRASS: '#7fb238'
      DIRT: '#976d4d'
      WATER: '#4040ff'
      STATIONARY_WATER: '#4040ff'
      LAVA: '#ffa500'
      STATIONARY_LAVA: '#ffa500'
      SAND: '#f7e9a3'
      LEAVES: '#007c00'
      SANDSTONE: '#f7e9a3'
      SNOW: '#ffffff'
      ICE: '#a0a0ff'
      SNOW_BLOCK: '#ffffff'
      PACKED_ICE: '#a0a0ff'
      FROSTED_ICE: '#a0a0ff'