name: "@PROJECT_NAME@"
version: "@VERSION@"
main: nl.rutgerkok.topographica.Topographica
author: Rutger Kok
permissions:
  cartographica.render:
    description: "Map rendering."
    default: op
  cartographica.admin:
    description: "Change @PROJECT_NAME@ settings."
    default: op
commands:
  render:
    description: "Renders a region."
    permission: "cartographica.render"
    usage: "/<command>"
