# Configuration file of @PROJECT_NAME@ v@VERSION@ (@DATE@)
# 
# EXPLANATION OF THE SETTINGS
# ... scroll down for the actual settings ...
# 
# timings:
#   These settings are used to make the plugin use less server resources.
#   The higher the numbers, the more time the server has to do other things,
#   and the slower the map will update.
#   pause-seconds-after-render-pass: 60
#     After everything on the server is rendered, the plugin will wait this amount of time
#     before starting a new render pass.
#   pause-seconds-after-chunk-load: 0.5
#     After the plugin needed to load a chunk, it will pause this amount of seconds before
#     continuing rendering.
#   no-pause-after-chunk-load-when-nobody-is-online: true
#     Set this to true to disable the chunk loading pause when there is nobody online. This
#     speeds up rendering when the server is empty.
#   
# web-server:
#   Here the internal web server is configured.
#   port: 
#     The port at which the web server listens. If you have set the port to
#     8088, then the map should appear in your web browser at
#     http://<your-server-ip>:8088/ . If it does not, then that port is probably
#     blocked. Look for errors in your console, try a different port or contact
#     your hosting provider.
#   web-root:
#     The map images are placed in this directory. Normally, this directory
#     resides inside plugins/@PROJECT_NAME@/ , but you can set the web root to
#     any writeable directory.
# 
# worlds:
#   Here each world can be configured. The world named "default" is used for all
#   worlds that do not have their own settings. The most important setting is
#   the radius. The radius is set in blocks, and controls how much of the world
#   is rendered around the center. A radius of 0 disables the map for that world.
#   The "order" setting controls the order of the worlds in the web browser menu.
#   Lower is earlier. If two worlds have the same order, the order in which they
#   appear is arbitrary.
#
# ACTUAL SETTINGS BELOW
timings:
  pause-seconds-after-render-pass: 60
  pause-seconds-after-chunk-load: 0.5
  no-pause-after-chunk-load-when-nobody-is-online: true
web-server:
  port: 8088
  web-root: web
  internal-web-server: true
worlds:
  default:
    radius: 2147483647
    max-blocking-time-nanoseconds-per-tick: 1000000
    colors:
      ACACIA_LEAVES: '#007c00'
      ACACIA_PLANKS: '#7f5d44'
      ACACIA_SLAB: '#7f5d44'
      ACACIA_STAIRS: '#7f5d44'
      AIR: '#000000'
      BEDROCK: '#0d0d0d'
      BIRCH_LEAVES: '#007c00'
      BIRCH_PLANKS: '#a6996f'
      BIRCH_SLAB: '#a6996f'
      BIRCH_STAIRS: '#a6996f'
      BLUE_ICE: '#a9cce3'
      COARSE_DIRT: '#5b3e28'
      CHISELED_QUARTZ_BLOCK: '#e7e3dd'
      DARK_OAK_LEAVES: '#007c00'
      DARK_OAK_PLANKS: '#382513'
      DARK_OAK_SLAB: '#382513'
      DARK_OAK_STAIRS: '#382513'
      DIORITE: '#c9c9c9'
      DIRT: '#976d4d'
      END_STONE: '#d6d99c'
      FROSTED_ICE: '#a0a0ff'
      GRANITE: '#946553'
      GRASS: '#7fb238'
      GRASS_BLOCK: '#7fb238'
      ICE: '#a0a0ff'
      JUNGLE_LEAVES: '#007c00'
      JUNGLE_PLANKS: '#7f5d44'
      JUNGLE_SLAB: '#7f5d44'
      JUNGLE_STAIRS: '#7f5d44'
      NETHERRACK: '#4b1717'
      LAVA: '#ffa500'
      NETHER_BRICKS: '#0d0305'
      OBSIDIAN: '#0d0818'
      OAK_LEAVES: '#007c00'
      OAK_PLANKS: '#856f4a'
      OAK_SLAB: '#856f4a'
      OAK_STAIRS: '#856f4a'
      ORANGE_TERRACOTTA: '#b7950b'
      PACKED_ICE: '#a0a0ff'
      POLISHED_DIORITE: '#d3d3d3'
      POLISHED_GRANITE: '#946553'
      PURPUR_BLOCK: '#a67aa5'
      QUARTZ_BLOCK: '#e7e3dd'
      QUARTZ_PILLAR: '#e7e3dd'
      RED_SAND: '#ff5733'
      SAND: '#f7e9a3'
      SANDSTONE: '#f7e9a3'
      SMOOTH_QUARTZ: '#e7e3dd'
      SNOW: '#ffffff'
      SNOW_BLOCK: '#ffffff'
      SOUL_SAND: '#3e2d22'
      SPRUCE_LEAVES: '#007c00'
      SPRUCE_PLANKS: '#57442c'
      SPRUCE_SLAB: '#57442c'
      SPRUCE_STAIRS: '#57442c'
      STONE: '#808080'
      TERRACOTTA: '#87472b'
      WATER: '#4040ff'
      WHITE_POWDERED_CONCRETE: '#dfe0e1'
