# Configuration file of @PROJECT_NAME@ v@VERSION@ (@DATE@)
# 
# EXPLANATION OF THE SETTINGS
# ... scroll down for the actual settings ...
# 
# web-server:
#   Here the internal web server is configured.
#   port: 
#     The port at which the web server listens. If you have set the port to
#     8088, then the map should appear in your web browser at
#     http://<your-server-ip>:8088/ . If it does not, then that port is probably
#     blocked. Look for errors in your console, try a different port or contact
#     your hosting provider.
#   web-root:
#     The map images are placed in this directory. Normally, this directory
#     resides inside plugins/@PROJECT_NAME@/ , but you can set the web root to
#     any writeable directory.
# 
# worlds:
#   Here each world can be configured. The world named "default" is used for all
#   worlds that do not have their own settings. The most important setting is
#   the radius. The radius is set in blocks, and controls how much of the world
#   is rendered around the center. A radius of 0 disables the map for that world.
# 
#   The setting max-blocking-time-nanoseconds-per-tick specifies for how long 
#   the plugin may block the whole server (in technical terms: run on the main
#   thread). The default value is 1 ms = 1000000 ns. A tick normally takes up to
#   50 ms, so there is still at least 49 ms available for all other processes on
#   the server. Increase this value to increase map rendering speed.
#
# ACTUAL SETTINGS BELOW
web-server:
  port: 8088
  web-root: web
  internal-web-server: true
worlds:
  default:
    radius: 2147483647
    max-blocking-time-nanoseconds-per-tick: 1000000
    colors:
      ACACIA_LEAVES: '#007c00'
      ACACIA_PLANKS: '#7f5d44'
      ACACIA_SLAB: '#7f5d44'
      ACACIA_STAIRS: '#7f5d44'
      AIR: '#000000'
      BLUE_ICE: '#A9CCE3'
      BIRCH_LEAVES: '#007c00'
      BIRCH_PLANKS: '#a6996F'
      BIRCH_SLAB: '#a6996F'
      BIRCH_STAIRS: '#a6996F'
      GRASS_BLOCK: '#7fb238'
      DARK_OAK_LEAVES: '#007c00'
      DARK_OAK_PLANKS: '#382513'
      DARK_OAK_SLAB: '#382513'
      DARK_OAK_STAIRS: '#382513'
      DIRT: '#976d4d'
      TERRACOTTA: '#87472b'
      ICE: '#a0a0ff'
      JUNGLE_LEAVES: '#007c00'
      JUNGLE_PLANKS: '#7F5d44'
      JUNGLE_SLAB: '#7F5d44'
      JUNGLE_STAIRS: '#7F5d44'
      LAVA: '#ffa500'
      OAK_LEAVES: '#007c00'
      OAK_PLANKS: '#856f4a'
      OAK_SLAB: '#856f4a'
      OAK_STAIRS: '#856f4a'
      ORANGE_TERRACOTTA: '#b7950b'
      RED_SAND: '#ff5733'
      SAND: '#f7e9a3'
      SANDSTONE: '#f7e9a3'
      SPRUCE_LEAVES: '#007c00'
      SPRUCE_PLANKS: '#57442c'
      SPRUCE_SLAB: '#57442c'
      SPRUCE_STAIRS: '#57442c'
      STONE: '#808080'
      WATER: '#4040ff'
      SNOW: '#ffffff'
      SNOW_BLOCK: '#ffffff'
      PACKED_ICE: '#a0a0ff'
      FROSTED_ICE: '#a0a0ff'